# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Littlelink"
license = "MIT"
licenselink = "https://github.com/kasperstad/littlelink/blob/master/LICENSE"
description = "LittleLink is an open source DIY self-hosted alternative to services like Linktree and many.link."
homepage = "https://littlelink.io"
tags = ["minimal", "landingpage", "responsive", "personal"]
features = []
min_version = "0.41.0"

[author]
  name = "Kasper Stad"
  homepage = "https://littlelink.io"

# If porting an existing theme
[original]
  name = "LittleLink"
  homepage = "https://littlelink.io"
  repo = "https://github.com/sethcottle/littlelink"
